#!/bin/sh
# Copyright (C) 2012-2014 PIVA Software <www.pivasoftware.com>
# 	Author: MOHAMED Kallel <mohamed.kallel@pivasoftware.com>
# 	Author: AHMED Zribi <ahmed.zribi@pivasoftware.com>
# Copyright (C) 2011-2012 Luka Perkov <freecwmp@lukaperkov.net>

get_wan_device_wan_connection_number() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionNumberOfEntries"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	  val="1"
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_ip_enable() {
	local nl="$1"
	local val=""
	local type="xsd:boolean"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Enable"
	local permissions="1"
	case "$action" in
		get_value)
		val=`$UCI_GET network.wan.auto 2> /dev/null`
		if [ $val -eq 1 ]; then
			val="enable"
		elif [ $val -eq 0 ]; then
			val="disable"
		else
			return $E_INTERNAL_ERROR
		fi
		;;
		get_name)
		[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
		;;
		get_notification)
		easycwmp_get_parameter_notification "val" "$parm"
		;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_enable() {
	local val=$1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Enable"
	case $action in
		set_value)
			case $val in
				disable|Disable|DISABLE)
					$UCI_SET network.wan.auto=0
					ifdown wan &
					;;
				enable|ENABLE|Enable)
					$UCI_SET network.wan.auto=1
					ifup wan &
					;;
				*)
					return $E_INVALID_PARAMETER_VALUE
					;;
			esac
		;;
		set_notification)
		easycwmp_set_parameter_notification "$parm" "$val"
		;;
	esac
}

get_wan_device_wan_ip_uptime() {
	local nl="$1"
	local val=""
	local type="xsd:unsignedInt"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Uptime"
	local permissions="0"
	case "$action" in
		get_value)
			local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
			# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test
			local errorval=`echo ${temp%%;*}`
			if [ "Error=0" == ${errorval} ]; then
			   	local tempval=`echo ${temp#*Uptime=}`
			   	val=`echo ${tempval%%;*}`
			else
				val="0"
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_last_conn_error() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.LastConnectionError"
	local permissions="0"
	case "$action" in
		get_value)
			local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
			# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test
			local errorval=`echo ${temp%%;*}`
			if [ "Error=0" == ${errorval} ]; then
			   	local tempval=`echo ${temp#*ConnectionStatus=}`
			   	val=`echo ${tempval%%;*}`
			else
				val="0"
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_addr_type() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.AddressingType"
	local nl="$1"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.proto 2> /dev/null`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_addr_type() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.AddressingType"
	local val=$1
	case $action in
		set_value)
			if [ "$val" = "dhcp" ] || [ "$val" = "static" ];then
				$UCI_SET network.wan.proto=$val
			else
				return $E_INVALID_PARAMETER_VALUE
			fi
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_max_mtu_size() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MaxMTUSize"
	local nl="$1"
	local val=""
	local type="xsd:unsignedInt"
	local permissions="1"
	case "$action" in
		get_value)
			# val=`$UCI_GET network.wan.mtu 2> /dev/null`
			val=`cat /sys/class/net/usb0/mtu`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_max_mtu_size() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MaxMTUSize"
	local val=$1
	case $action in
		set_value)
			if [ $val -gt 0 ] && [ $val -le 1540 ]; then
				$UCI_SET network.wan.mtu=$val
				$UCI_COMMIT network
			else
				return $E_INVALID_PARAMETER_VALUE
			fi
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_conn_trigger() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionTrigger"
	local nl="$1"
	local val=""
	local permissions="0"
	case "$action" in
		get_value)
			val="AlwaysOn"
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_x_alu_ipv4_enable() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv4Enable"
	local nl="$1"
	local val=""
	local type="xsd:boolean"
	local permissions="0"
	case "$action" in
		get_value)
			local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
			local errorval=`echo ${temp%%;*}`
			if [ "Error=0" == ${errorval} ]; then
				local tempval=${temp#*ConnectionType=}
				val=${tempval%%;*}
			else
				val=""
			fi
			if [ "$val" = "PDP_TYPE_IPv4" ] || [ "$val" = "PDP_TYPE_IPv4v6" ];then
				val="enable"
			else
				val="disable"
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv4_enable() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv4Enable"
	local val=$1
	case $action in
		set_value)
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_x_alu_ipv6_enable() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Enable"
	local nl="$1"
	local val=""
	local type="xsd:boolean"
	local permissions="0"
	case "$action" in
		get_value)
			local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
			local errorval=`echo ${temp%%;*}`
			if [ "Error=0" == ${errorval} ]; then
				local tempval=${temp#*ConnectionType=}
				val=${tempval%%;*}
			else
				val=""
			fi
			if [ "$val" = "PDP_TYPE_IPv6" ] || [ "$val" = "PDP_TYPE_IPv4v6" ];then
				val="enable"
			else
				val="disable"
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv6_enable() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Enable"
	local val=$1
	case $action in
		set_value)
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_x_alu_ipv6_status() {
# TODO: Unconfigured ; Connecting ; Connected ; PendingDisconnect ; Disconneting ; Disconnected
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6ConnectionStatus"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	if [ "Error=0" == ${errorval} ]; then
	   	local tempval=${temp#*ConnectionStatus=}
	   	val=${tempval%%;*}
	else
		val="1"
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_ip_x_alu_ipv6_addr_type() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6AddressingType"
	local nl="$1"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.proto > /dev/null`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv6_addr_type() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6AddressingType"
	local val=$1
	case $action in
		set_value)
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_x_alu_ipv6_defaultgateway() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DefaultGateway"
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.proto` > /dev/null
			if [ "$val" = "static" ];then
				# should be fix
				val=`$UCI_GET network.wan.gateway`> /dev/null
			else
				val=""
				# return $E_INVALID_ARGUMENTS
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv6_defaultgateway() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DefaultGateway"
	local val=$1
	case $action in
		set_value)
			val=`$UCI_GET network.wan.proto` > /dev/null
			if [ "$val" = "static" ];then
				# should be fix
				$UCI_SET network.wan.gateway=$val
				$UCI_COMMIT network
			else
				return $E_INVALID_ARGUMENTS
			fi
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_x_alu_ipv6_dns_enabled() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSEnabled"
	local permissions="1"
	case "$action" in
		get_value)
			val=""
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv6_dns_enabled() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSEnabled"
	local val=$1
	case $action in
		set_value)
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_x_alu_ipv6_dns_servers() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSServers"
	local permissions="1"
	case "$action" in
		get_value)
			val=""
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv6_dns_servers() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSServers"
	local val=$1
	case $action in
		set_value)
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_x_alu_ipv6_address() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Address"
	local nl="$1"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
			local errorval=`echo ${temp%%;*}`
			if [ "Error=0" = ${errorval} ]; then
			   local tempval=`echo ${temp#*ExternalIPv6Address=}`
			   val=`echo ${tempval%%;*}`
			else
			  val=""
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_x_alu_ipv6_address() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Address"
	local val=$1
	case $action in
		set_value)
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_status() {
# TODO: Unconfigured ; Connecting ; Connected ; PendingDisconnect ; Disconneting ; Disconnected
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionStatus"
local permissions="0"
case "$action" in
	get_value)
	#Updated by Tian Yiqing, Get wan status from RILD, start
	#val="Connected"
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test
	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   	local tempval=`echo ${temp#*ConnectionStatus=}`
	   	val=`echo ${tempval%%;*}`
	else
		val="1"
	fi
	#Updated by Tian Yiqing, Get wan status from RILD, end
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_ip_external_ipaddr() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress"
local permissions="0"
case "$action" in
	get_value)
	#Modified by Tian Yiqing, Get wan interface ip address from Rild, start
#	if [ -z "$default_wan_device_mng_interface_ip" ]; then
#		network_get_ipaddr val mng
#	else
#		val=$default_wan_device_mng_interface_ip
#	fi

	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" = ${errorval} ]; then
	   local tempval=`echo ${temp#*ExternalIPv4Address=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="1"
	fi
	#Modified by Tian Yiqing, Get wan interface ip address from Rild, end
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_ip_subnetmask() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.SubnetMask"
	local permissions="0"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.proto` > /dev/null
			if [ "$val" = "static" ];then
				# should be fix
				val=`$UCI_GET network.wan.netmask`> /dev/null
			else
				val=""
				# return $E_INVALID_ARGUMENTS
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

get_wan_device_wan_ip_defaultgateway() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DefaultGateway"
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.proto` > /dev/null
			if [ "$val" = "static" ];then
				# should be fix
				val=`$UCI_GET network.wan.gateway`> /dev/null
			else
				val=""
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_defaultgateway() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DefaultGateway"
	local val=$1
	case $action in
		set_value)
			val=`$UCI_GET network.wan.proto` > /dev/null
			if [ "$val" = "static" ];then
				# should be fix
				$UCI_SET network.wan.gateway=$val
				$UCI_COMMIT network
			else
				return $E_INVALID_ARGUMENTS
			fi
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_connection_type() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionType"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*ConnectionType=}`
	   val=`echo ${tempval%%;*}`
	else
		val=""
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_ip_dns_enable() {
	local nl="$1"
	local val=""
	local type="xsd:boolean"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSEnabled"
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.peerdns` > /dev/null
			if [ "$val" = "1" ];then
				val="true"
			else
				val="false"
			fi
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_dns_enable() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSEnabled"
	local val=$1
	case $action in
		set_value)
			if [ "$val" = "true" ];then
				$UCI_SET network.wan.peerdns=1
			elif [ "$val" = "false" ]; then
				$UCI_SET network.wan.peerdns=0
			else
				return $E_INVALID_PARAMETER_VALUE
			fi
			$UCI_COMMIT network
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_dns_servers() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSServers"
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET network.wan.dns` > /dev/null
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions"
	return 0
}

set_wan_device_wan_ip_dns_servers() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSServers"
	local val=$1
	case $action in
		set_value)
			$UCI_SET network.wan.dns=$val
			$UCI_COMMIT network
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_stats_eth_bytes_sent() {
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetBytesSent"
	local nl="$1"
	local val=""
	local type="xsd:unsignedInt"
	local permissions="0"
	case "$action" in
		get_value)
		local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
		local errorval=`echo ${temp%%;*}`
		if [ "Error=0" == ${errorval} ]; then
		   local tempval=`echo ${temp#*TotalBytesSent=}`
		   val=`echo ${tempval%%;*}`
		else
		  val="0"
		fi
		;;

		get_name)
		[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
		;;

		get_notification)
		easycwmp_get_parameter_notification "val" "$parm"
		;;

	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_stats_eth_bytes_received() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetBytesReceived"
	local type="xsd:unsignedInt"
	local permissions="0"
	case "$action" in
		get_value)
		local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
		local errorval=`echo ${temp%%;*}`
		if [ "Error=0" == ${errorval} ]; then
		   local tempval=`echo ${temp#*TotalBytesReceived=}`
		   val=`echo ${tempval%%;*}`
		else
		  val="0"
		fi
		;;

		get_name)
		[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
		;;

		get_notification)
		easycwmp_get_parameter_notification "val" "$parm"
		;;

	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_stats_eth_packets_sent() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetPacketsSent"
	local type="xsd:unsignedInt"
	local permissions="0"
	case "$action" in
		get_value)
		val=`ifconfig |grep -A 6 usb0|grep "TX packets"|awk '{print $2}'|awk -F ":" '{print $2}'`
		;;

		get_name)
		[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
		;;

		get_notification)
		easycwmp_get_parameter_notification "val" "$parm"
		;;

	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_stats_eth_packets_received() {
	local nl="$1"
	local val=""
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetPacketsReceived"
	local type="xsd:unsignedInt"
	local permissions="0"
	case "$action" in
		get_value)
		val=`ifconfig |grep -A 6 usb0|grep "RX packets"|awk '{print $2}'|awk -F ":" '{print $2}'`
		;;

		get_name)
		[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
		;;

		get_notification)
		easycwmp_get_parameter_notification "val" "$parm"
		;;

	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_num_entries() {
	local nl="$1"
	local val=""
	local type="xsd:unsignedInt"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMappingNumberOfEntries"
	local permissions="0"
	case "$action" in
		get_value)
			val=`uci show firewall |grep "firewall.\@redirect\[[0-9]\+\]\=redirect"|wc -l`
			;;
		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;
		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_enable() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local val=""
	local type="xsd:boolean"
	local permissions="1"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingEnabled"
	case "$action" in
		get_value)
			val=`$UCI_GET firewall.@redirect[$i].enabled`
			;;
		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;
		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;
	esac
	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_enable() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingEnabled"
	case "$action" in
		set_value)
			if [ "$val" = "0" ] || [ "$val" = "1" ];then
				$UCI_SET firewall.@redirect[$i].enabled="$val"
				$UCI_COMMIT firewall
			else
				return $E_INVALID_PARAMETER_VALUE
			fi
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac
}

get_wan_device_wan_ip_port_map_lease_time() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local val=""
	local type="xsd:unsignedInt"
	local permissions="1"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingLeaseDuration"
	case "$action" in
		get_value)
			val="0"
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_lease_time() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingLeaseDuration"
	case "$action" in
		set_value)
			;;
		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_remote_host() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.RemoteHost"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			val="0"
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_remote_host() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.RemoteHost"
	case "$action" in
		set_value)
			;;
		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_external_port() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.ExternalPort"
	local val=""
	local type="xsd:unsignedInt"
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET firewall.@redirect[$i].src_dport`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_external_port() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.ExternalPort"
	case "$action" in
		set_value)
			$UCI_SET firewall.@redirect[$i].src_dport=$val
			$UCI_COMMIT firewall
			;;
		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_internal_port() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.InternalPort"
	local val=""
	local type="xsd:unsignedInt"
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET firewall.@redirect[$i].dest_port`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_internal_port() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.InternalPort"
	case "$action" in
		set_value)
			[ "$val" = "0" ] return $E_INVALID_PARAMETER_VALUE
			$UCI_SET firewall.@redirect[$i].dest_port=$val
			$UCI_COMMIT firewall
			;;
		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_protocol() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingProtocol"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET firewall.@redirect[$i].proto`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_protocol() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingProtocol"
	case "$action" in
		set_value)
			case $val in
				tcp|TCP|Tcp)
					$UCI_SET firewall.@redirect[$i].proto="tcp"
					;;
				udp|UDP|Udp)
					$UCI_SET firewall.@redirect[$i].proto="udp"
					;;
				"tcp/udp"|"udp/tcp"|"Tcp/Udp"|"Udp/Tcp"|"TCP/UDP"|"UDP/TCP")
					$UCI_SET firewall.@redirect[$i].proto="tcp udp"
					;;
				*)
					return $E_INVALID_PARAMETER_VALUE
					;;
			esac
			$UCI_COMMIT firewall
			;;

		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_internal_client() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.InternalClient"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			val=`$UCI_GET firewall.@redirect[$i].dest_ip`
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_internal_client() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.InternalClient"
	case "$action" in
		set_value)
			$UCI_SET firewall.@redirect[$i].dest_ip="$val"
			$UCI_COMMIT firewall
			;;
		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_port_map_description() {
	local num=$1
	local i
	let   i=$num-1
	local nl="$2"
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingDescription"
	local val=""
	local permissions="1"
	case "$action" in
		get_value)
			val=""
			;;

		get_name)
			[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
			;;

		get_notification)
			easycwmp_get_parameter_notification "val" "$parm"
			;;

	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

set_wan_device_wan_ip_port_map_description() {
	local num="$1"
	local val="$2"
	local i
	let   i=$num-1
	local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num.PortMappingDescription"
	case "$action" in
		set_value)
			;;
		set_notification)
			easycwmp_set_parameter_notification "$parm" "$val"
			;;
	esac

	easycwmp_output "$parm" "$val" "$permissions" "$type"
	return 0
}

get_wan_device_wan_ip_conn_num() {
local nl="$1"
local val=""
local type="xsd:unsignedInt"
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnectionNumberOfEntries"
local permissions="0"
case "$action" in
	get_value)
	  val="1"
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac

easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_mng_interface_ppp_connection_num() {
local nl="$1"
local val=""
local type="xsd:unsignedInt"
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnectionNumberOfEntries"
local permissions="0"
case "$action" in
	get_value)
	  val="1"
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac

easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_ip_macaddr() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress"
local permissions="0"
case "$action" in
	get_value)
	#Modified by Tian Yiqing, Get wan interface mac address from Rild, start
#	if [ -z "$default_wan_device_mng_interface_mac" ]; then
#		val=`$UCI_GET network.mng.macaddr`
#	else
#		val=$default_wan_device_mng_interface_mac
#	fi

	val=`cat /sys/class/net/usb0/address 2> /dev/null`
#	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
#
#	local errorval=`echo ${temp%%;*}`
#	if [ "Error=0" == ${errorval} ]; then
#	   local tempval=`echo ${temp#*MACAddress=}`
#	   val=`echo ${tempval%%;*}`
#	else
#	  val="1"
#	fi
	#Modified by Tian Yiqing, Get wan interface mac address from Rild, end
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_common_interface_enable_internet() {
local nl="$1"
local val=""
local type="xsd:boolean"
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.EnabledForInternet"
local permissions="1"
case "$action" in
	get_value)
	ifconfig | grep usb0 > /dev/null
	if [ $? -eq 0 ];then
		val="1"
	else
		val="0"
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

set_wan_device_wan_common_interface_enable_internet() {
local val=$1
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.EnabledForInternet"
case "$action" in
	set_value)
	ifconfig | grep usb0 > /dev/null
	if [ "$val" -eq 1 ];then
		ifconfig usb0 up &
	elif [ "$val" -eq 0 ];then
		ifconfig usb0 down &
	else
		return $E_INVALID_PARAMETER_VALUE
	fi
	;;
	set_notification)
	easycwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wan_device_wan_common_interface_wan_access_type() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.WANAccessType"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*AccessType=}`
	   val=`echo ${tempval%%;*}`
	else
	  val=""
	fi
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_common_interface_upstream_max_bit_rate() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Layer1UpstreamMaxBitRate"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*UpStringMaxBitRate=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="0"
	fi
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_common_interface_downstream_max_bit_rate() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Layer1DownstreamMaxBitRate"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*DownStringMaxBitRate=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="0"
	fi
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_common_interface_phy_link_status() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.PhysicalLinkStatus"
local permissions="0"
case "$action" in
	get_value)
	ifconfig | grep usb0 > /dev/null
	if [ $? -eq 0 ];then
		val="Up"
	else
		val="Down"
	fi
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_common_interface_total_bytes_sent() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalBytesSent"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*TotalBytesSent=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="0"
	fi
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_common_interface_total_bytes_received() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalBytesReceived"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*TotalBytesReceived=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="0"
	fi
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_common_interface_total_packets_sent() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalPacketsSent"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	val=`ifconfig |grep -A 6 usb0|grep "TX packets"|awk '{print $2}'|awk -F ":" '{print $2}'`
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_common_interface_total_packets_received() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalPacketsReceived"
local type="xsd:unsignedInt"
local permissions="0"
case "$action" in
	get_value)
	val=`ifconfig |grep -A 6 usb0|grep "RX packets"|awk '{print $2}'|awk -F ":" '{print $2}'`
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;

	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;

esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

get_wan_device_wan_ppp_enable() {
local nl="$1"
local val=""
local type="xsd:boolean"
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Enable"
local permissions="1"
case "$action" in
	get_value)
	val=`$UCI_GET network.wan.auto 2> /dev/null`
	if [ -z $val ]; then
		val="1"
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions" "$type"
return 0
}

set_wan_device_wan_ppp_enable() {
local val=$1
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Enable"
case $action in
	set_value)
	if [ "$val" -eq 0 ]; then
		$UCI_SET network.wan.auto=0
		ifdown wan &
	elif [ "$val" -eq 1 ]; then
		$UCI_SET network.wan.auto=1
		ifup wan &
	else
		return $E_INVALID_PARAMETER_VALUE
	fi
	;;
	set_notification)
	easycwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

# fix
get_wan_device_wan_ppp_connection_status() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.ConnectionStatus"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*ConnectionStatus=}`
	   val=`echo ${tempval%%;*}`
	else
	  val=""
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

# fix
get_wan_device_wan_ppp_connection_type() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.ConnectionType"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*ConnectionType=}`
	   val=`echo ${tempval%%;*}`
	else
		val=""
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_wan_ppp_username() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Username"
local permissions="1"
case "$action" in
	get_value)
	#val=`$UCI_GET network.wan.username 2> /dev/null`
	#Modified by Tian Yiqing, Get wan connection username from Rild, Start
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
	# temp='Error=0;ConnectionStatus=conn_status;Username=username;Password=password;ExternalIPv4Address=ipv4;ExternalIPv6Address= ipv6;MACAddress=mac_addr;' #test

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*Username=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="1"
	fi
	#Modified by Tian Yiqing, Get wan connection username from Rild, end
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

set_wan_device_wan_ppp_username() {
local val=$1
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Username"
case $action in
	set_value)
	$UCI_SET network.wan.username="$val"
	;;
	set_notification)
	easycwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

get_wan_device_wan_ppp_password() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Password"
local permissions="1"
case "$action" in
	get_value)
	#Modified by Tian Yiqing, Get wan connection password from Rild, Start
	#val=`$UCI_GET network.wan.password 2> /dev/null`
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*Password=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="1"
	fi
	#Modified by Tian Yiqing, Get wan connection password from Rild, end
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

set_wan_device_wan_ppp_password() {
local val=$1
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Password"
case $action in
	set_value)
	$UCI_SET network.wan.password="$1"
	;;
	set_notification)
	easycwmp_set_parameter_notification "$parm" "$val"
	;;
esac
}

# fix
get_wan_device_wan_ppp_external_ipaddr() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.ExternalIPAddress"
local permissions="0"
case "$action" in
	get_value)
	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`

	local errorval=`echo ${temp%%;*}`
	if [ "Error=0" == ${errorval} ]; then
	   local tempval=`echo ${temp#*ExternalIPv4Address=}`
	   val=`echo ${tempval%%;*}`
	else
	  val="1"
	fi
	;;
	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

# fix
get_wan_device_wan_ppp_mac_addr() {
local nl="$1"
local val=""
local parm="InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.MACAddress"
local permissions="0"
case "$action" in
	get_value)
#	local temp=`cd /usr/share/easycwmp/oem;lua tr069_extend_api.lua GetConnectionState`
#
#	local errorval=`echo ${temp%%;*}`
#	if [ "Error=0" == ${errorval} ]; then
#	   local tempval=`echo ${temp#*Password=}`
#	   val=`echo ${tempval%%;*}`
#	else
#	  val="1"
#	fi

	val=""
	;;

	get_name)
	[ "$nl" = "1" ] &&  return $E_INVALID_ARGUMENTS
	;;
	get_notification)
	easycwmp_get_parameter_notification "val" "$parm"
	;;
esac
easycwmp_output "$parm" "$val" "$permissions"
return 0
}

get_wan_device_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice." "" "0"
	;;
esac
}

get_wan_device_instance() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1." "" "0"
	;;
esac
}

get_wan_device_wan_common_interface_config_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig." "" "0"
	;;
esac
}

get_wan_device_wan_common_interface_config_connection_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Connection." "" "0"
	;;
esac
}

get_wan_device_wan_common_interface_config_connection_instance() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Connection.1." "" "0"
	;;
esac
}

get_wan_device_wan_connection_device_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice." "" "0"
	;;
esac
}

get_wan_device_wan_connection_device_instance() {
nl="$1"
case "$action" in
	get_name)
	if [ "$nl" = "0" ]; then
		[ "$2" != "2" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1." "" "0"
		[ "$2" != "1" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2." "" "0"
	fi
	;;
esac
}

get_wan_device_wan_connection_device_wan_ip_connection_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection." "" "0"
	;;
esac
}

get_wan_device_wan_connection_device_wan_ip_connection_instance() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1." "" "0"
	;;
esac
}

get_wan_device_wan_connection_device_wan_ip_connection_stats_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats." "" "0"
	;;
esac
}

get_wan_device_wan_connection_device_wan_ip_connection_port_map_object() {
	nl="$1"
	case "$action" in
		get_name)
			[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping." "" "1"
			;;
	esac
}

get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance() {
	nl="$1"
	case "$action" in
		get_name)
			[ "$nl" != "0" ] && return
			local val=`uci show firewall |grep "firewall.\@redirect\[[0-9]\+\]\=redirect"|wc -l`
			local i=1
			if [ "$val" = "" ];then
				return
			fi

			while [ $i -le $val ]
			do
				easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$i." "" "1"
				let i=$i+1
			done
			;;
	esac
}

get_wan_device_wan_connection_device_wan_ip_connection_port_map_each_instance() {
	num="$1"
	nl="$2"
	case "$action" in
		get_name)
			[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.$num." "" "1"
			;;
	esac
}

get_wan_device_wan_connection_device_wan_ppp_connection_object() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection." "" "0"
	;;
esac
}

get_wan_device_wan_connection_device_wan_ppp_connection_instance() {
nl="$1"
case "$action" in
	get_name)
	[ "$nl" = "0" ] && easycwmp_output "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1." "" "0"
	;;
esac
}

get_wan_device_wan_ip_info() {
	get_wan_device_wan_ip_enable $1
	get_wan_device_wan_ip_uptime $1
	# get_wan_device_wan_ip_last_conn_error $1
	get_wan_device_wan_ip_status "$1"
	get_wan_device_wan_ip_addr_type $1
	get_wan_device_wan_ip_max_mtu_size $1
	get_wan_device_wan_ip_external_ipaddr "$1"
	# get_wan_device_wan_ip_subnetmask $1
	# get_wan_device_wan_ip_defaultgateway $1
	get_wan_device_wan_ip_connection_type "$1"
	# get_wan_device_wan_ip_dns_enable $1
	# get_wan_device_wan_ip_dns_servers $1
	get_wan_device_wan_ip_macaddr "$1"
	get_wan_device_wan_ip_conn_trigger "$1"

	get_wan_device_wan_ip_x_alu_ipv4_enable "$1"
	get_wan_device_wan_ip_x_alu_ipv6_enable "$1"
	get_wan_device_wan_ip_x_alu_ipv6_status "$1"
#	get_wan_device_wan_ip_x_alu_ipv6_addr_type "$1"
#	get_wan_device_wan_ip_x_alu_ipv6_defaultgateway "$1"
#	get_wan_device_wan_ip_x_alu_ipv6_dns_enabled "$1"
#	get_wan_device_wan_ip_x_alu_ipv6_dns_servers "$1"
	get_wan_device_wan_ip_x_alu_ipv6_address "$1"

	get_wan_device_wan_ip_port_map_num_entries $1
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_object $1
}

get_wan_device_wan_ip_port_map_info() {
	if [ "$2" = "" ];then
		local val=`uci show firewall |grep "firewall.\@redirect\[[0-9]\+\]\=redirect"|wc -l`
		local num=1
		while [ $num -le $val ]
		do
			get_wan_device_wan_ip_port_map_enable "$num" "$1"
			# get_wan_device_wan_ip_port_map_lease_time "$num" "$1"
			# get_wan_device_wan_ip_port_map_remote_host "$num" "$1"
			get_wan_device_wan_ip_port_map_external_port "$num" "$1"
			get_wan_device_wan_ip_port_map_internal_port "$num" "$1"
			get_wan_device_wan_ip_port_map_protocol "$num" "$1"
			get_wan_device_wan_ip_port_map_internal_client "$num" "$1"
			get_wan_device_wan_ip_port_map_description "$num" "$1"
			let num=$num+1
		done
	else
			get_wan_device_wan_ip_port_map_enable "$1"
			# get_wan_device_wan_ip_port_map_lease_time "$1"
			# get_wan_device_wan_ip_port_map_remote_host "$1"
			get_wan_device_wan_ip_port_map_external_port "$1"
			get_wan_device_wan_ip_port_map_internal_port "$1"
			get_wan_device_wan_ip_port_map_protocol "$1"
			get_wan_device_wan_ip_port_map_internal_client "$1"
			get_wan_device_wan_ip_port_map_description "$1"
	fi
}

get_wan_device_wan_ip_stats_eth_info() {
	get_wan_device_wan_ip_stats_eth_bytes_sent $1
	get_wan_device_wan_ip_stats_eth_bytes_received $1
	get_wan_device_wan_ip_stats_eth_packets_sent $1
	get_wan_device_wan_ip_stats_eth_packets_received $1
}

get_wan_device_wan_ppp_config() {
	get_wan_device_wan_ppp_enable "$1"
	get_wan_device_wan_ppp_connection_status "$1"
	get_wan_device_wan_ppp_connection_type "$1"
	get_wan_device_wan_ppp_username "$1"
	get_wan_device_wan_ppp_password "$1"
	get_wan_device_wan_ppp_external_ipaddr "$1"
	get_wan_device_wan_ppp_mac_addr "$1"
}

get_wan_device_wan_common_interface_config() {
	get_wan_device_wan_common_interface_enable_internet "$1"
	get_wan_device_wan_common_interface_wan_access_type "$1"
	get_wan_device_wan_common_interface_upstream_max_bit_rate "$1"
	get_wan_device_wan_common_interface_downstream_max_bit_rate "$1"
	get_wan_device_wan_common_interface_phy_link_status "$1"
	get_wan_device_wan_common_interface_total_bytes_sent "$1"
	get_wan_device_wan_common_interface_total_bytes_received "$1"
	get_wan_device_wan_common_interface_total_packets_sent "$1"
	get_wan_device_wan_common_interface_total_packets_received "$1"
}

get_wan_device() {
case "$1" in
	InternetGatewayDevice.)
	get_wan_device_object 0
	get_wan_device_instance "$2"
	get_wan_device_wan_connection_number "$2"
	get_wan_device_wan_connection_device_object "$2"
	get_wan_device_wan_common_interface_config_object "$2"
	get_wan_device_wan_common_interface_config_connection_object "$2"
	get_wan_device_wan_common_interface_config_connection_instance "$2"
	get_wan_device_wan_connection_device_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_object "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
	# get_wan_device_wan_connection_device_wan_ppp_connection_object "$2"
	# get_wan_device_wan_connection_device_wan_ppp_connection_instance "$2"
	get_wan_device_wan_ip_conn_num "$2"
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	# get_wan_device_mng_interface_ppp_connection_num "$2"
	get_wan_device_wan_ip_info $2
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_common_interface_config $2
	# get_wan_device_wan_common_interface_config_active_connection_device_container "$2"
	# get_wan_device_wan_common_interface_config_active_connection_service_id "$2"

	# get_wan_device_wan_ppp_config $2

	get_radio_info_object "$2"
	get_radio_info_instance "$2"
	get_radio_info_params_all "$2"
	get_profile_list_object "$2"
	get_profile_list_instance "$2"
	get_profile_instance_params_all "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.)
	get_wan_device_object "$2"
	get_wan_device_instance 0
	get_wan_device_wan_connection_number "$2"
	get_wan_device_wan_connection_device_object "$2"
	get_wan_device_wan_common_interface_config_object "$2"
	get_wan_device_wan_common_interface_config_connection_object "$2"
	get_wan_device_wan_common_interface_config_connection_instance "$2"
	get_wan_device_wan_connection_device_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_object "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
	# get_wan_device_wan_connection_device_wan_ppp_connection_object "$2"
	# get_wan_device_wan_connection_device_wan_ppp_connection_instance "$2"
	get_wan_device_wan_ip_conn_num "$2"
	# get_wan_device_mng_interface_ppp_connection_num "$2"
	get_wan_device_wan_ip_info $2
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	get_wan_device_wan_common_interface_config $2
	# get_wan_device_wan_common_interface_config_active_connection_device_container "$2"
	# get_wan_device_wan_common_interface_config_active_connection_service_id "$2"
	# get_wan_device_wan_ppp_config $2

	get_radio_info_object "$2"
	get_radio_info_instance "$2"
	get_radio_info_params_all "$2"
	get_profile_list_object "$2"
	get_profile_list_instance "$2"
	get_profile_instance_params_all "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.)
	get_wan_device_instance "$2"
	get_wan_device_wan_connection_number 0
	get_wan_device_wan_connection_device_object 0
	get_wan_device_wan_common_interface_config_object 0
	get_wan_device_wan_common_interface_config_connection_object "$2"
	get_wan_device_wan_common_interface_config_connection_instance "$2"
	get_wan_device_wan_connection_device_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_object "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
	# get_wan_device_wan_connection_device_wan_ppp_connection_object "$2"
	# get_wan_device_wan_connection_device_wan_ppp_connection_instance "$2"
	get_wan_device_wan_ip_conn_num "$2"
	# get_wan_device_mng_interface_ppp_connection_num "$2"
	get_wan_device_wan_ip_info $2
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	get_wan_device_wan_common_interface_config $2
	# get_wan_device_wan_common_interface_config_active_connection_device_container "$2"
	# get_wan_device_wan_common_interface_config_active_connection_service_id "$2"
	# get_wan_device_wan_ppp_config $2

	get_radio_info_object 0
	get_radio_info_instance "$2"
	get_radio_info_params_all "$2"
	get_profile_list_object "$2"
	get_profile_list_instance "$2"
	get_profile_instance_params_all "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.)
	get_radio_info_params_all 0
	get_profile_list_object 0
	get_profile_list_instance "$2"
	get_profile_instance_params_all "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.X_ALU_APNName)
	get_current_apn_name 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.NetworkPriority)
	get_radio_info_network_priority 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.ExternalAntenna)
	get_radio_info_external_antenna 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.ServiceStatus)
	get_radio_info_service_status 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.PLMN)
	get_radio_info_plmn 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RAT)
	get_radio_info_rat 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.LTEBand)
	get_radio_info_lte_band 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSSI.Combined)
	get_radio_info_rssi_combined 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSSI.Antenna1)
	get_radio_info_rssi_antenna1 0
	return $?
	;;

#	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSSI.Antenna2)
#	get_radio_info_rssi_antenna2 0
#	return $?
#	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRP.Combined)
	get_radio_info_rsrp_combined 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRP.Antenna1)
	get_radio_info_rsrp_antenna1 0
	return $?
	;;

#	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRP.Antenna2)
#	get_radio_info_rsrp_antenna2 0
#	return $?
#	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRQ.Combined)
	get_radio_info_rsrq_combined 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRQ.Antenna1)
	get_radio_info_rsrq_antenna1 0
	return $?
	;;

#	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRQ.Antenna2)
#	get_radio_info_rsrq_antenna2 0
#	return $?
#	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSCP)
	get_radio_info_rscp 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.ECNO)
	get_radio_info_ecno 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.IMEI)
	get_radio_info_imei 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.IMSI)
	get_radio_info_imsi 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.PhysicalCellID)
	get_radio_info_physical_cellid 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.CellID)
	get_radio_info_cellid 0
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.)
	get_profile_list_object 0
	get_profile_list_instance 0
	get_profile_instance_params_all "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.)
	get_profile_list_instance 0
	get_profile_instance_params_all "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}." "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_params_by_id "$2" "$nums"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.APNName)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.APNName" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_apnname "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.APN)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.APN" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_apn "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.AuthenticationProtocol)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.AuthenticationProtocol" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_auth "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.Username)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.Username" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_username "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.Password)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.Password" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_password "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.DialNumber)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.DialNumber" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	get_profile_instance_dial_number "$nums" "$2"
	return $?
	;;


	InternetGatewayDevice.WANDevice.1.WANConnectionNumberOfEntries)
	get_wan_device_wan_connection_number "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.)
	get_wan_device_wan_connection_device_object "$2"
	get_wan_device_wan_connection_device_instance 0
	get_wan_device_wan_connection_device_wan_ip_connection_object "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
	# get_wan_device_wan_connection_device_wan_ppp_connection_object "$2"
	# get_wan_device_wan_connection_device_wan_ppp_connection_instance "$2"
	get_wan_device_wan_ip_conn_num "$2"
	# get_wan_device_mng_interface_ppp_connection_num "$2"
	get_wan_device_wan_ip_info $2
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	# get_wan_device_wan_ppp_config $2
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.)
	get_wan_device_wan_common_interface_config_object "$2"
	get_wan_device_wan_common_interface_config_connection_object 0
	get_wan_device_wan_common_interface_config_connection_instance "$2"
	get_wan_device_wan_common_interface_config 0
	# get_wan_device_wan_common_interface_config_active_connection_device_container "$2"
	# get_wan_device_wan_common_interface_config_active_connection_service_id "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Connection.)
	get_wan_device_wan_common_interface_config_connection_instance 0
	# get_wan_device_wan_common_interface_config_active_connection_device_container "$2"
	# get_wan_device_wan_common_interface_config_active_connection_service_id "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Connection.1.)
	get_wan_device_wan_common_interface_config_connection_instance "$2"
	# get_wan_device_wan_common_interface_config_active_connection_device_container 0
	# get_wan_device_wan_common_interface_config_active_connection_service_id 0
	return 0
	;;

	# InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Connection.1.ActiveConnectionDeviceContainer)
	# get_wan_device_wan_common_interface_config_active_connection_device_container "$2"
	# return $?
	# ;;

	# InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Connection.1.ActiveConnectionServiceID)
	# get_wan_device_wan_common_interface_config_active_connection_service_id "$2"
	# return $?
	# ;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.EnabledForInternet)
	get_wan_device_wan_common_interface_enable_internet "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.WANAccessType)
	get_wan_device_wan_common_interface_wan_access_type "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Layer1UpstreamMaxBitRate)
	get_wan_device_wan_common_interface_upstream_max_bit_rate "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.Layer1DownstreamMaxBitRate)
	get_wan_device_wan_common_interface_downstream_max_bit_rate "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.PhysicalLinkStatus)
	get_wan_device_wan_common_interface_phy_link_status "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalBytesSent)
	get_wan_device_wan_common_interface_total_bytes_sent "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalBytesReceived)
	get_wan_device_wan_common_interface_total_bytes_received "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalPacketsSent)
	get_wan_device_wan_common_interface_total_packets_sent "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.TotalPacketsReceived)
	get_wan_device_wan_common_interface_total_packets_received "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.)
	get_wan_device_wan_connection_device_instance "$2" "1"
	get_wan_device_wan_connection_device_wan_ip_connection_object 0
	get_wan_device_wan_connection_device_wan_ip_connection_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
	get_wan_device_wan_ip_conn_num 0
	get_wan_device_wan_ip_info $2
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	return 0
	;;
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.)
	get_wan_device_wan_connection_device_instance "$2" "2"
	# get_wan_device_wan_connection_device_wan_ppp_connection_object 0
	# get_wan_device_wan_connection_device_wan_ppp_connection_instance "$2"
	# get_wan_device_mng_interface_ppp_connection_num 0
	# get_wan_device_wan_ppp_config $2
	return 0
	;;
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.)
	get_wan_device_wan_connection_device_wan_ip_connection_object "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_instance 0
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
	get_wan_device_wan_ip_info $2
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	return 0
	;;
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.)
	get_wan_device_wan_connection_device_wan_ip_connection_instance "$2"
	get_wan_device_wan_connection_device_wan_ip_connection_stats_object 0
	get_wan_device_wan_ip_info 0
	get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance $2
	get_wan_device_wan_ip_port_map_info $2
	get_wan_device_wan_ip_stats_eth_info $2
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.)
		get_wan_device_wan_connection_device_wan_ip_connection_stats_object $2
		get_wan_device_wan_ip_stats_eth_info 0
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetBytesSent)
		get_wan_device_wan_ip_stats_eth_bytes_sent $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetBytesReceived)
		get_wan_device_wan_ip_stats_eth_bytes_received $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetPacketsSent)
		get_wan_device_wan_ip_stats_eth_packets_sent $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Stats.EthernetPacketsReceived)
		get_wan_device_wan_ip_stats_eth_packets_received $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.)
	get_wan_device_wan_connection_device_wan_ppp_connection_object "$2"
	get_wan_device_wan_connection_device_wan_ppp_connection_instance 0
	# get_wan_device_wan_ppp_config $2
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnectionNumberOfEntries)
	get_wan_device_wan_ip_conn_num "$2"
	return $?
	;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnectionNumberOfEntries)
#	get_wan_device_mng_interface_ppp_connection_num "$2"
#	return $?
#	;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.)
#	get_wan_device_wan_connection_device_wan_ppp_connection_instance "$2"
#	get_wan_device_wan_ppp_config 0
#	return 0
#	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Enable)
		get_wan_device_wan_ip_enable "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Uptime)
		get_wan_device_wan_ip_uptime $2
		return $?
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.LastConnectionError)
#		get_wan_device_wan_ip_last_conn_error $2
#		return $?
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.AddressingType)
		get_wan_device_wan_ip_addr_type $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MaxMTUSize)
		get_wan_device_wan_ip_max_mtu_size $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionTrigger)
		get_wan_device_wan_ip_conn_trigger "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv4Enable)
		get_wan_device_wan_ip_x_alu_ipv4_enable "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Enable)
		get_wan_device_wan_ip_x_alu_ipv6_enable "$2"
		return $?
		;;
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6ConnectionStatus)
		get_wan_device_wan_ip_x_alu_ipv6_status "$2"
		return $?
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6AddressingType)
#		get_wan_device_wan_ip_x_alu_ipv6_addr_type "$2"
#		return $?
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DefaultGateway)
#		get_wan_device_wan_ip_x_alu_ipv6_defaultgateway "$2"
#		return $?
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSEnabled)
#		get_wan_device_wan_ip_x_alu_ipv6_dns_enabled "$2"
#		return $?
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSServers)
#		get_wan_device_wan_ip_x_alu_ipv6_dns_servers "$2"
#		return $?
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Address)
		get_wan_device_wan_ip_x_alu_ipv6_address "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionStatus)
		get_wan_device_wan_ip_status "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress)
		get_wan_device_wan_ip_external_ipaddr "$2"
		return $?
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.SubnetMask)
#		get_wan_device_wan_ip_subnetmask $2
#		return $?
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DefaultGateway)
#		get_wan_device_wan_ip_defaultgateway $2
#		return $?
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionType)
		get_wan_device_wan_ip_connection_type $2
		return $?
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSEnabled)
#		get_wan_device_wan_ip_dns_enable $2
#		return $?
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSServers)
#		get_wan_device_wan_ip_dns_servers $2
#		return $?
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress)
		get_wan_device_wan_ip_macaddr "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMappingNumberOfEntries)
		get_wan_device_wan_ip_port_map_num_entries $2
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.)
		get_wan_device_wan_connection_device_wan_ip_connection_port_map_object $2
		get_wan_device_wan_connection_device_wan_ip_connection_port_map_all_instance 0
		get_wan_device_wan_ip_port_map_info $2
		return 0
		;;

# Notice:the "*" of "[0-9]*" is wildcard of the shell, not the symbol of the regular. If there are objects follow by the "[0-9]*"
# it will be error. for exemple:the object "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.xxx."
# will be match the case "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*."
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}." "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_connection_device_wan_ip_connection_port_map_each_instance "$num" $2
		get_wan_device_wan_ip_port_map_info "$num" 0
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.PortMappingEnabled)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.PortMappingEnabled" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_ip_port_map_enable "$num" "$2"
		return $?
		;;

# H850 unsupport the below features
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[1-9]|[1-9][0-9].PortMappingLeaseDuration)
#		get_wan_device_wan_ip_port_map_lease_time $2
#		return $?
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[1-9]|[1-9][0-9].RemoteHost)
#		get_wan_device_wan_ip_port_map_remote_host $2
#		return $?
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.ExternalPort)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.ExternalPort" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_ip_port_map_external_port "$num" "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.InternalPort)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.InternalPort" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_ip_port_map_internal_port "$num" "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.PortMappingProtocol)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.PortMappingProtocol" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_ip_port_map_protocol "$num" "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.InternalClient)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.InternalClient" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_ip_port_map_internal_client "$num" "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.PortMappingDescription)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.InternalClient" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		get_wan_device_wan_ip_port_map_description "$num" "$2"
		return $?
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Enable)
#	get_wan_device_wan_ppp_enable "$2"
#	return $?
#	;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.ConnectionStatus)
#	get_wan_device_wan_ppp_connection_status "$2"
#	return $?
#	;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.ConnectionType)
#	get_wan_device_wan_ppp_connection_type "$2"
#	return $?
#	;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Username)
#	get_wan_device_wan_ppp_username "$2"
#	return $?
#	;;
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Password)
#	get_wan_device_wan_ppp_password "$2"
#	return $?
#	;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.ExternalIPAddress)
#	get_wan_device_wan_ppp_external_ipaddr "$2"
#	return $?
#	;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.MACAddress)
#	get_wan_device_wan_ppp_mac_addr "$2"
#	return $?
#	;;
esac
return $E_INVALID_PARAMETER_NAME
}

set_wan_device() {
case "$1" in
	InternetGatewayDevice.WANDevice.|\
	InternetGatewayDevice.WANDevice.1.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.)
	[ "$action" = "set_value" ] && return $E_INVALID_PARAMETER_NAME
	easycwmp_set_parameter_notification "$1" "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MACAddress|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ConnectionStatus|\
	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.ExternalIPAddress|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.NetworkPriority|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.ExternalAntenna|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.ServiceStatus|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.PLMN|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RAT|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.LTEBand|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSSI.Combined|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSSI.Antenna1|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSSI.Antenna2|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRP.Combined|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRP.Antenna1|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRP.Antenna2|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRQ.Combined|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRQ.Antenna1|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSRQ.Antenna2|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.RSCP|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.ECNO|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.IMEI|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.IMSI|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.PhysicalCellID|\
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.CellID)
	[ "$action" = "set_value" ] && return $E_NON_WRITABLE_PARAMETER
	easycwmp_set_parameter_notification "$1" "$2"
	return 0
	;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.Enable)
		set_wan_device_wan_ip_enable "$2"
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.AddressingType)
		# set_wan_device_wan_ip_addr_type $2
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.MaxMTUSize)
		# set_wan_device_wan_ip_max_mtu_size $2
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv4Enable)
		# set_wan_device_wan_ip_x_alu_ipv4_enable "$2"
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Enable)
		# set_wan_device_wan_ip_x_alu_ipv6_enable "$2"
		return 0
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6AddressingType)
#		set_wan_device_wan_ip_x_alu_ipv6_addr_type "$2"
#		return 0
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DefaultGateway)
#		set_wan_device_wan_ip_x_alu_ipv6_defaultgateway "$2"
#		return 0
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSEnabled)
#		set_wan_device_wan_ip_x_alu_ipv6_dns_enabled "$2"
#		return 0
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6DNSServers)
#		set_wan_device_wan_ip_x_alu_ipv6_dns_servers "$2"
#		return 0
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.X_ALU_IPv6Address)
		set_wan_device_wan_ip_x_alu_ipv6_address "$2"
		return $?
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DefaultGateway)
		set_wan_device_wan_ip_defaultgateway $2
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSEnabled)
		set_wan_device_wan_ip_dns_enable $2
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.DNSServers)
		set_wan_device_wan_ip_dns_servers $2
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.PortMappingEnabled)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.PortMappingEnabled" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		set_wan_device_wan_ip_port_map_enable "$num" "$2"
		return 0
		;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.PortMappingLeaseDuration)
#		set_wan_device_wan_ip_port_map_lease_time $2
#		return 0
#		;;
#
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.1.RemoteHost)
#		set_wan_device_wan_ip_port_map_remote_host $2
#		return 0
#		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.ExternalPort)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.ExternalPort" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		set_wan_device_wan_ip_port_map_external_port "$num" "$2"
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.InternalPort)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.InternalPort" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		set_wan_device_wan_ip_port_map_internal_port "$num" "$2"
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.PortMappingProtocol)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.PortMappingProtocol" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		set_wan_device_wan_ip_port_map_protocol "$num" "$2"
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.InternalClient)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.{i}.InternalClient" "rc" "num"
		[ "$num" = "" ] return $E_INVALID_PARAMETER_NAME
		set_wan_device_wan_ip_port_map_internal_client "$num" "$2"
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.1.WANIPConnection.1.PortMapping.[0-9]*.PortMappingDescription)
		set_wan_device_wan_ip_port_map_description $2
		return 0
		;;

	InternetGatewayDevice.WANDevice.1.WANCommonInterfaceConfig.EnabledForInternet)
	set_wan_device_wan_common_interface_enable_internet "$2"
	return 0
	;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Enable)
#	set_wan_device_wan_ppp_enable "$2"
#	return 0
#	;;

#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Username)
#	#Modified by Tian Yiqing, Disable set wan username, Start
#	#set_wan_device_wan_ppp_username "$2"
#	#Modified by Tian Yiqing, Disable set wan username, End
#	return 0
#	;;
#	InternetGatewayDevice.WANDevice.1.WANConnectionDevice.2.WANPPPConnection.1.Password)
#	#Modified by Tian Yiqing, Disable set wan password, Start
#	#set_wan_device_wan_ppp_password "$2"
#	#Modified by Tian Yiqing, Disable set wan password, End
#	return 0
#	;;
	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.APNName)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.APNName" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	set_profile_instance_apnname "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.APN)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.APN" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	set_profile_instance_apn "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.AuthenticationProtocol)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.AuthenticationProtocol" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	set_profile_instance_auth "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.Username)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.Username" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	set_profile_instance_username "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.Password)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.Password" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	set_profile_instance_password "$nums" "$2"
	return $?
	;;

	InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.DialNumber)
	easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}.DialNumber" "rc" "nums"
	[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
	set_profile_instance_dial_number "$nums" "$2"
	return $?
	;;

	# add by Zhao Zijun begin
    # *)
	# echo "*********************************************************************************************"
	# echo "Warning: \"$1\" is not searched out."
	# echo "         Please check the parameter what you enter whether support!"
	# echo "*********************************************************************************************"
	# return $E_INVALID_PARAMETER_NAME
	# ;;
	# add by Zhao Zijun end

esac
return $E_INVALID_PARAMETER_NAME
}

build_instances_wan_device() { return 0; }

add_object_wan_device()
{
	case "$1" in
		InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.)
		local instance=`add_device_radio_info`
		#easycwmp_set_parameter_notification "$1$instance." "0"
		easycwmp_status_output "" "" "1" "$instance"
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}

delete_object_wan_device()
{
	local nums
	case "$1" in
		InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.[0-9]*.)
		easycwmp_parse_formated_parameter "$1" "InternetGatewayDevice.WANDevice.1.X_ALU_RadioInfo.1.X_ALU_APN.{i}." "rc" "nums"
		[ "$rc" != "0" ] && return $E_INVALID_PARAMETER_NAME
		delete_device_radio_info $nums
		easycwmp_remove_parameter_notification "$1"
		easycwmp_status_output "" "" "1"
		return 0
		;;
	esac
	return $E_INVALID_PARAMETER_NAME
}
