#!/bin/sh /etc/rc.common
#
# Copyright (c) 2014 TCL Communication Technology Holdings LTD.
#
# All Rights Reserved.
# TCL Confidential and Proprietary.
#

# We don't want to start ART2 automatically at boot time as we want the
# default to be a working user configuration.
# At the end of the boot process, the user can start art using:
# /etc/init.d/art start
START=
SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

MTD_ART_PART_NAME="art"

unload_wifi_modules() {
	wifi down
	rmmod ath9k
}

unload_art_modules() {
	rmmod art
}

load_art_modules() {
	insmod art
}

start() {
	# ART2 conflicts with the WiFi driver so we don't start anything here
	# We'll just prepare the field in case we want to start nart.out
	[ -c /dev/dk0 ] || mknod /dev/dk0 c 63 0

	mtd_name=$(grep ${MTD_ART_PART_NAME} /proc/mtd | cut -f1 -d:)
	[ -L /dev/caldata ] || \
		ln -s /dev/${mtd_name//mtd/mtdblock} /dev/caldata

	unload_wifi_modules

 	load_art_modules

	# Start the daemon
	/usr/sbin/nart.out  -console
}

stop() {
	unload_art_modules

	rm /dev/dk0
	rm /dev/caldata
}
