#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2014 OpenWrt.org

START=99

boot() {
	uci set easycwmp.@ping_diagnostics[0].DiagnosticsState='None'
	uci set easycwmp.@DownloadDiagnostics[0].DiagnosticsState='None'
	uci set easycwmp.@UploadDiagnostics[0].DiagnosticsState='None'
	uci commit easycwmp
        service_start /usr/sbin/easycwmpd --boot
}

start() {
	uci set easycwmp.@ping_diagnostics[0].DiagnosticsState='None'
	uci set easycwmp.@DownloadDiagnostics[0].DiagnosticsState='None'
	uci set easycwmp.@UploadDiagnostics[0].DiagnosticsState='None'
	uci commit easycwmp
        service_start /usr/sbin/easycwmpd --getrpcmethod
}

stop() {
        service_stop /usr/sbin/easycwmpd
}
