#!/bin/sh
	
	
	uci set network.eth=interface
	uci set network.eth.ifname='eth0.2'
	uci set network.eth.proto='dhcp'
	
	uci del network.@switch_vlan[1]
	uci add network switch_vlan
	uci set network.@switch_vlan[0].vlan='1'
	uci set network.@switch_vlan[0].ports='0t 2 3 4 5'
	uci set network.@switch_vlan[0].vid='1'
	
	uci set network.@switch_vlan[1].device='eth0'
	uci set network.@switch_vlan[1].vlan='2'
	uci set network.@switch_vlan[1].ports='0t 1'
	uci set network.@switch_vlan[1].vid='2'
	
	uci reorder network.eth=3
	uci reorder network.@switch_vlan[1]=6
	
	uci set firewall.@zone[1].network='eth'
	
	uci commit network
	uci commit firewall		
	
	/etc/init.d/network restart
	/etc/init.d/firewall restart

	
