#!/bin/sh /etc/rc.common

START=20
STOP=90

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

start() {
	stop
	[ -e /proc/sys/kernel/core_pattern ] && {
		ulimit -c unlimited
		echo '/tmp/%e.%p.%s.%t.core' > /proc/sys/kernel/core_pattern
	}
	service_start /sbin/netifd

	setup_switch() { return 0; }

	include /lib/network
	setup_switch

	#sleep 5    # lqc cancel

	/sbin/wifi down
	/sbin/wifi up

	echo 1 > /proc/sys/net/ipv6/conf/eth0/disable_ipv6
        LINKADDR=$(ifconfig br-lan | awk '/inet6/ {print $3}')
        ip -6 addr del ${LINKADDR} dev br-lan
        ip -6 addr add fe80::1/64 dev br-lan

}

restart() {
	ifdown -a
	sleep 1
	start
}

shutdown() {
	ifdown -a
	stop
}

stop() {
	service_stop /sbin/netifd
}

reload() {
	ubus call network reload
	/sbin/wifi down
	/sbin/wifi up
}
