#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=60
start() {
        config_load quagga
        local enabled
        config_get_bool enabled ripd enabled 1
        
        [ $enabled -gt 0 ] || return 1

        /usr/sbin/quagga.init start
}

stop() {
        /usr/sbin/quagga.init stop
}