#!/bin/sh
# Copyright (C) 2006 OpenWrt.org

run_scripts() {
	for i in /etc/rc.d/$1*; do
		[ -x $i ] && $i $2 2>&1
	done | $LOGGER
}

system_config() {
	config_get_bool foreground $1 foreground 0
}

LOGGER="cat"
[ -x /usr/bin/logger ] && LOGGER="logger -s -p 6 -t sysinit"

. /lib/functions.sh

config_load system
config_foreach system_config system

if [ "$1" = "S" -a "$foreground" != "1" ]; then
	run_scripts "$1" "$2" &
else
	run_scripts "$1" "$2"
fi

software_version_backup=$(uci get webs_cfg.system.SwVersion)
software_version_new=H850_00_12.09_20

if [ "$software_version_backup" != "$software_version_new" ];then
        uci set webs_cfg.system.SwVersion=$software_version_new
        uci commit webs_cfg
fi
