xmpp_client_demo:xmpp_client_demo.o
	$(CC) $(LDFLAGS) xmpp_client_demo.o -o xmpp_client_demo
xmpp_client_demo.o:xmpp_client_demo.c
	$(CC) $(CFLAGS) -c xmpp_client_demo.c
clean:
	rm *.o xmpp_client_demo

