//==========================================================================
/**
 *  @file    rild_api.h
 *  @brief  The definition for error ids, message ids.
 *  @version 1.0
 *  @author Tian Yiqing <yiqing.tian@tcl.com>
 *  @date 2013-10-15
 */
//==========================================================================

#ifndef RILD_API_H
#define RILD_API_H

enum
{
    RILD_ERRID_SUCCESS = 0,
    RILD_ERRID_FAILED = 1,
    RILD_ERRID_BAD_PARAMETER = 2,
    RILD_ERRID_DEVICE_NOT_READY = 3,
    RILD_ERRID_COMM_OPEN_FAILED = 4,
    RILD_ERRID_AT_INIT_ERROR = 5,
    RILD_ERRID_RPC_WRITE_FAILED = 6,
    RILD_ERRID_RPC_DISCONNECTED = 7,
    RILD_ERRID_AT_ERROR_TIMEOUT = 8,
    RILD_ERRID_AT_ERROR_NOT_ENOUGH_MEMORY = 9,
    RILD_ERRID_AT_ERROR_CALLBACK_FUNC_IS_NOT_READY = 10,
    RILD_ERRID_AT_ERROR_PHSIM_PIN_REQUIRED = 11,
    RILD_ERRID_AT_ERROR_PHFSIM_PIN_REQUIRED = 12,
    RILD_ERRID_AT_ERROR_PHFSIM_PUK_REQUIRED = 13,
    RILD_ERRID_AT_ERROR_SIM_NOT_INSERTED = 14,
    RILD_ERRID_AT_ERROR_SIM_PIN_REQUIRED = 15,
    RILD_ERRID_AT_ERROR_SIM_PUK_REQUIRED = 16,
    RILD_ERRID_AT_ERROR_SIM_FAILURE = 17,
    RILD_ERRID_AT_ERROR_SIM_BUSY = 18,
    RILD_ERRID_AT_ERROR_SIM_WRONG = 19,
    RILD_ERRID_AT_ERROR_INCORRECT_PASSWORD = 20,
    RILD_ERRID_AT_ERROR_SIM_PIN2_REQUIRED = 21,
    RILD_ERRID_AT_ERROR_SIM_PUK2_REQUIRED = 22,
    RILD_ERRID_AT_ERROR_PHNET_PIN_REQUIRED = 23,
    RILD_ERRID_AT_ERROR_PHNET_PUK_REQUIRED = 24,
    RILD_ERRID_AT_ERROR_PHNETSUB_PIN_REQUIRED = 25,
    RILD_ERRID_AT_ERROR_PHNETSUB_PUK_REQUIRED = 26,
    RILD_ERRID_AT_ERROR_PHSP_PIN_REQUIRED = 27,
    RILD_ERRID_AT_ERROR_PHSP_PUK_REQUIRED = 28,
    RILD_ERRID_AT_ERROR_PHCORP_PIN_REQUIRED = 29,
    RILD_ERRID_AT_ERROR_PHCORP_PUK_REQUIRED = 30,
    RILD_ERRID_AT_ERROR_PIN_VERIFY_OK_BUT_FAIL_TO_DISABLE_PIN = 31,
    RILD_ERRID_AT_ERROR_CALL_NO_CARRIER = 32,
    RILD_ERRID_AT_ERROR_CALL_NO_ANSWER = 33,
    RILD_ERRID_AT_ERROR_CALL_BUSY = 34,
    RILD_ERRID_AT_ERROR_CALL_NO_DIAL_TONE = 35,
    RILD_ERRID_AT_ERROR_CALL_INVALID_NUMBER = 36,
    RILD_ERRID_AT_ERROR_CALL_AUDIO_INVALID = 37,
    RILD_ERRID_AT_ERROR_PB_STORAGE_IS_FULL = 38,
    RILD_ERRID_AT_ERROR_PB_NO_NEED_TO_MOVE = 39,
    RILD_ERRID_AT_ERROR_PB_ITEM_SAVED_BUT_OLD_ONE_REMAINED = 40,
    RILD_ERRID_CANCELED_MANUALLY = 41,
    RILD_ERRID_NO_MESSAGE = 42,
    RILD_ERRID_ERROR_USER_DEFINE_ERROR = 43,
    RILD_ERRID_SOCKET_ERROR = 44,
    RILD_ERRID_PROFILE_STORAGE_IS_FULL = 45,
    RILD_ERRID_PROFILE_NO_ACTIVE = 46,
    RILD_ERRID_SMS_STORAGE_IS_FULL = 47,
    RILD_ERRID_SMS_SENDING_LAST_MESSAGE = 48,
    RILD_ERRID_TOO_MANY_REQUEST = 49,
    RILD_ERRID_AT_BUSY = 50,
    RILD_ERRID_USSD_SENDING_LAST = 51,
    RILD_ERRID_USAGE_HISTORY_OVERFLOW = 52
};

enum
{
    RILD_MSGID_INVALID = 0,

    RILD_DEVICEMSG_PIN_CHECK_STATE = 1,
    RILD_DEVICEMSG_PIN_ENABLE = 2,
    RILD_DEVICEMSG_PIN_GET_INFO = 3,
    RILD_DEVICEMSG_PIN_CHANGE = 4,
    RILD_DEVICEMSG_PIN_VERIFY = 5,
    RILD_DEVICEMSG_PIN_VERIFY_PUK = 6,
    RILD_DEVICEMSG_PIN_GET_STATE = 7,

    RILD_DEVICEMSG_NETWORK_GET_INFO = 100,
    RILD_DEVICEMSG_NETWORK_GET_LIST = 101,
    RILD_DEVICEMSG_NETWORK_GET_LIST_RESULT = 102,
    RILD_DEVICEMSG_NETWORK_SET = 103,
    RILD_DEVICEMSG_NETWORK_INIT = 104,
    RILD_DEVICEMSG_NETWORK_GET_REG_STATE = 105,
    RILD_DEVICEMSG_NETWORK_SET_BAND = 106,
    RILD_DEVICEMSG_NETWORK_GET_BAND = 107,
    RILD_DEVICEMSG_NETWORK_SET_MODE = 108,
    RILD_DEVICEMSG_NETWORK_GET_MODE = 109,
    RILD_DEVICEMSG_NETWORK_GET_SDN_LIST = 110,
    RILD_DEVICEMSG_NETWORK_GET_LAC_AND_CELLID = 111,
    RILD_DEVICEMSG_NETWORK_GET_EC_IO = 112,
    RILD_DEVICEMSG_NETWORK_GET_RSCP = 113,
    RILD_DEVICEMSG_NETWORK_REGISTER = 114,
    RILD_DEVICEMSG_GET_NETWORK_LOC_INFO = 115,
    RILD_DEVICEMSG_NETWORK_SEARCH_CANCEL = 116,
    RILD_DEVICEMSG_NETWORK_GET_MODE_EX = 117,
    RILD_DEVICEMSG_NETWORK_SET_MODE_EX = 118,
#ifdef JRD_NETWORK_EXTEND
    RILD_DEVICEMSG_NETWORK_GET_LIST_EX = 119,
    RILD_DEVICEMSG_NETWORK_GET_LIST_RESULT_EX = 120,
    RILD_DEVICEMSG_NETWORK_SEARCH_CANCEL_EX = 121,
    RILD_DEVICEMSG_NETWORK_REGISTER_EX = 122,
    RILD_DEVICEMSG_NETWORK_GET_REGISTER_RESULT_EX = 123,
#endif
    RILD_DEVICEMSG_NETWORK_GET_SIGNAL_VALUE = 124,
    RILD_DEVICEMSG_NETWORK_GET_LTE_BAND_EX = 125,

    RILD_DEVICEMSG_SYSTEM_GET_EQUIPMENT_INFO = 200,
    RILD_DEVICEMSG_SYSTEM_GET_DIAG_INFO = 201,
    RILD_DEVICEMSG_SYSTEM_GET_MSISDN = 202,
    RILD_DEVICEMSG_SYSTEM_GET_CUREF = 203,
    RILD_DEVICEMSG_SYSTEM_GET_ICCID = 204,
    RILD_DEVICEMSG_SYSTEM_GET_MOD_LINUX_VER = 205,
    RILD_DEVICEMSG_SYSTEM_MOD_UPGRADE = 206,
    RILD_DEVICEMSG_SYSTEM_MOD_MULTISTEP_UPGRADE = 207,
    RILD_DEVICEMSG_SYSTEM_GET_MOD_UPGRADE_STATUS = 208,
    RILD_DEVICEMSG_SYSTEM_GET_IMSI = 209,
    RILD_DEVICEMSG_SYSTEM_RESET_MODULE = 210,

    RILD_DEVICEMSG_CALL_DIAL_EM = 300,
    RILD_DEVICEMSG_CALL_DIAL = 301,
    RILD_DEVICEMSG_CALL_ANSWER = 302,
    RILD_DEVICEMSG_CALL_HANGUP = 303,
    RILD_DEVICEMSG_CALL_SENDDTMF = 304,
    RILD_DEVICEMSG_CALL_INIT = 305,
    RILD_DEVICEMSG_CALL_GET_STATE = 306,
    RILD_DEVICEMSG_CALL_JREJECT = 307,

    RILD_DEVICEMSG_SMS_INIT = 400,
    RILD_DEVICEMSG_SMS_GET_LIST = 401,
    RILD_DEVICEMSG_SMS_DELETE = 402,
    RILD_DEVICEMSG_SMS_SEND = 403,
    RILD_DEVICEMSG_SMS_SAVE = 404,
    RILD_DEVICEMSG_SMS_GET_STORAGE_INFO = 405,
    RILD_DEVICEMSG_SMS_MODIFY_TAG = 406,
    RILD_DEVICEMSG_SMS_SET_SC = 407,
    RILD_DEVICEMSG_SMS_GET_SC = 408,
    RILD_DEVICEMSG_SMS_SET_PREFERRED_STORAGE = 409,
    RILD_DEVICEMSG_SMS_GET_PREFERRED_STORAGE = 410,
    RILD_DEVICEMSG_SMS_GET_SETTINGS = 411,
    RILD_DEVICEMSG_SMS_SET_SETTINGS = 412,
    RILD_DEVICEMSG_SMS_SEND_CANCEL = 413,
    RILD_DEVICEMSG_SMS_GET_SEND_PROGRESS = 414,
    RILD_DEVICEMSG_SMS_GET_COUNT = 415,

    RILD_DEVICEMSG_RECEIVE_SMS_RPT = 500,
    RILD_DEVICEMSG_USSD_RECEIVE_RPT = 501,
    RILD_DEVICEMSG_CALL_RING_PRPT = 502,
    RILD_DEVICEMSG_CALL_BUSY_PRPT = 503,
    RILD_DEVICEMSG_CALL_NO_ANSWER_PRPT = 504,
    RILD_DEVICEMSG_CALL_NO_CARRIER_PRPT = 505,
    RILD_DEVICEMSG_CALL_NO_DIALTONE_PRPT = 506,
    RILD_DEVICEMSG_CALL_JCONNECTED_PRPT = 507,
    RILD_DEVICEMSG_CALL_JENDCALL_PRPT = 508,
    RILD_DEVICEMSG_CALL_JRING_PRPT = 509,
    RILD_DEVICEMSG_STK_PROACTIVECMD_RPT = 510,
    RILD_DEVICEMSG_CALL_CHANGE_STATE_RPT = 511,
    RILD_DEVICEMSG_SYSTEM_MODULE_UPGRADE_PRPT = 512,
    RILD_DEVICEMSG_SEND_SMS_RPT = 513,

    RILD_DEVICEMSG_CONN_WAN_CONNECT = 600,
    RILD_DEVICEMSG_CONN_WAN_DISCONNECT = 601,
    RILD_DEVICEMSG_CONN_GET_PROFILE_LIST = 602, //include profile_id, profile_pdp_type, profile_apn, profile_pdp_addr, profile_d_comp, profile_h_comp, profile_is_active, profile_auth_type, profile_username, profile_passwd
    RILD_DEVICEMSG_CONN_ADD_PROFILE = 603,
    RILD_DEVICEMSG_CONN_DELETE_PROFILE = 604,
    RILD_DEVICEMSG_CONN_UPDATE_PROFILE_INFO = 605,
    RILD_DEVICEMSG_CONN_ACTIVE_PROFILE = 606,
    RILD_DEVICEMSG_CONN_GET_WAN_INFO = 607, //including traffics, connection state, ip address, duration
    RILD_DEVICEMSG_CONN_GET_CONNECTION_TYPE = 608,
    RILD_DEVICEMSG_CONN_SET_CONNECTION_TYPE = 609,

    RILD_DEVICEMSG_GET_AUTO_PIN_STATE = 700,
    RILD_DEVICEMSG_SET_AUTO_PIN_STATE = 701,

    RILD_DEVICEMSG_GET_CALL_LOG_LIST = 800,
    RILD_DEVICEMSG_DELETE_CALL_LOG = 801,
    RILD_DEVICEMSG_CLEAR_CALL_LOG = 802,

    RILD_DEVICEMSG_USSD_SEND = 900,
    RILD_DEVICEMSG_USSD_GET_SEND_RESULT = 901,
    RILD_DEVICEMSG_USSD_CANCEL = 902,

    RILD_TIMER_SYSTEM_GET_EQUIPMENT_INFO = 1000,
    RILD_TIMER_NETWORK_GET_INFO = 1001,
    RILD_TIMER_CONN_GET_WAN_CONNECTION_STATE = 1002,
    RILD_TIMER_CHECK_AUTO_PIN = 1003,
    RILD_TIMER_SMS_GET_IMSI = 1004,
    RILD_TIMER_CALL_CHECK_STATE = 1005,
    RILD_TIMER_SYSTEM_GET_IMSI = 1006,
    RILD_TIMER_USSD_SEND_TIMEOUT = 1007,

    RILD_TEST_SEND_COMMAND = 1100,
    RILD_CLIENT_SET_PERSISTENT = 1101,
    RILD_MSGID_MAX = 1200
};

enum
{
    RILD_MSG_PRIORITY_VERY_LOW,
    RILD_MSG_PRIORITY_LOW,
    RILD_MSG_PRIORITY_NORMAL,
    RILD_MSG_PRIORITY_HIGH,
    RILD_MSG_PRIORITY_VERY_HIGH
};

#endif // RILD_API_H
